name: Test & Build

on:
  push:
    branches:
    - main
    paths:
    - app/**
    - app_wear/**
    - film_log_wear_data/**
    - flutter_wear_os_connectivity/**
    - flutter_wear_os_location/**
  pull_request:

jobs:
  test_and_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: corretto
        java-version: "17"
        cache: gradle

    - name: Setup Flutter SDK
      uses: flutter-actions/setup-flutter@v3
      with:
        channel: stable
        version: "3.22.3"
        cache: "true"
        cache-sdk: "true"

    - name: Test flutter_wear_os_location
      working-directory: flutter_wear_os_location
      run: |-
        flutter pub get
        flutter test

    - name: Test & build phone app
      working-directory: app
      run: |-
        flutter pub get
        flutter test
        flutter build appbundle --debug

    - name: Test & build Wear OS app
      working-directory: app_wear
      run: |-
        flutter pub get
        flutter test
        flutter build appbundle --debug
